// Kosovo TV Example preset data
export const kosovoExampleData = {
  opening_time: 420,
  closing_time: 1380,
  min_duration: 30,
  max_duration: 120,
  min_score: 10,
  max_score: 100,
  max_consecutive_genre: 2,
  channels_count: 13,
  switch_penalty: 3,
  termination_penalty: 15,
  priority_blocks: [
    {
      start: 720,
      end: 780,
      allowed_channels: [0, 1, 3],
    },
    {
      start: 1200,
      end: 1380,
      allowed_channels: [0, 3, 5, 6],
    },
  ],
  time_preferences: [
    {
      start: 420,
      end: 600,
      preferred_genre: "news",
      bonus: 30,
    },
    {
      start: 600,
      end: 780,
      preferred_genre: "talk",
      bonus: 20,
    },
    {
      start: 780,
      end: 1020,
      preferred_genre: "drama",
      bonus: 25,
    },
    {
      start: 1020,
      end: 1260,
      preferred_genre: "movie",
      bonus: 40,
    },
    {
      start: 1260,
      end: 1380,
      preferred_genre: "music",
      bonus: 15,
    },
  ],
  channels: [
    {
      channel_id: 0,
      channel_name: "RTK1",
      programs: [
        {
          start: 420,
          end: 480,
          genre: "news",
          score: 51,
        },
        {
          start: 480,
          end: 540,
          genre: "news",
          score: 72,
        },
        {
          start: 540,
          end: 600,
          genre: "kids",
          score: 98,
        },
        {
          start: 600,
          end: 690,
          genre: "movie",
          score: 44,
        },
        {
          start: 690,
          end: 780,
          genre: "music",
          score: 49,
        },
        {
          start: 780,
          end: 900,
          genre: "talk",
          score: 78,
        },
        {
          start: 900,
          end: 990,
          genre: "drama",
          score: 53,
        },
        {
          start: 990,
          end: 1080,
          genre: "movie",
          score: 54,
        },
        {
          start: 1080,
          end: 1140,
          genre: "drama",
          score: 68,
        },
        {
          start: 1140,
          end: 1170,
          genre: "kids",
          score: 72,
        },
        {
          start: 1170,
          end: 1200,
          genre: "news",
          score: 89,
        },
        {
          start: 1200,
          end: 1230,
          genre: "news",
          score: 71,
        },
        {
          start: 1230,
          end: 1320,
          genre: "drama",
          score: 81,
        },
        {
          start: 1320,
          end: 1380,
          genre: "news",
          score: 86,
        },
      ],
    },
    {
      channel_id: 1,
      channel_name: "RTK2",
      programs: [
        {
          start: 420,
          end: 450,
          genre: "sports",
          score: 41,
        },
        {
          start: 450,
          end: 570,
          genre: "kids",
          score: 59,
        },
        {
          start: 570,
          end: 660,
          genre: "kids",
          score: 89,
        },
        {
          start: 660,
          end: 750,
          genre: "talk",
          score: 41,
        },
        {
          start: 750,
          end: 870,
          genre: "news",
          score: 54,
        },
        {
          start: 870,
          end: 930,
          genre: "kids",
          score: 62,
        },
        {
          start: 930,
          end: 1050,
          genre: "news",
          score: 44,
        },
        {
          start: 1050,
          end: 1140,
          genre: "movie",
          score: 61,
        },
        {
          start: 1140,
          end: 1200,
          genre: "kids",
          score: 46,
        },
        {
          start: 1200,
          end: 1230,
          genre: "music",
          score: 82,
        },
        {
          start: 1230,
          end: 1350,
          genre: "kids",
          score: 42,
        },
        {
          start: 1350,
          end: 1380,
          genre: "sports",
          score: 88,
        },
      ],
    },
    {
      channel_id: 2,
      channel_name: "KTV",
      programs: [
        {
          start: 420,
          end: 480,
          genre: "kids",
          score: 93,
        },
        {
          start: 480,
          end: 540,
          genre: "drama",
          score: 96,
        },
        {
          start: 540,
          end: 630,
          genre: "talk",
          score: 60,
        },
        {
          start: 630,
          end: 660,
          genre: "kids",
          score: 47,
        },
        {
          start: 660,
          end: 720,
          genre: "news",
          score: 62,
        },
        {
          start: 720,
          end: 810,
          genre: "kids",
          score: 69,
        },
        {
          start: 810,
          end: 870,
          genre: "kids",
          score: 63,
        },
        {
          start: 870,
          end: 900,
          genre: "news",
          score: 83,
        },
        {
          start: 900,
          end: 1020,
          genre: "music",
          score: 56,
        },
        {
          start: 1020,
          end: 1080,
          genre: "talk",
          score: 63,
        },
        {
          start: 1080,
          end: 1170,
          genre: "sports",
          score: 49,
        },
        {
          start: 1170,
          end: 1260,
          genre: "sports",
          score: 76,
        },
        {
          start: 1260,
          end: 1350,
          genre: "kids",
          score: 49,
        },
        {
          start: 1350,
          end: 1380,
          genre: "talk",
          score: 73,
        },
      ],
    },
  ],
};

